<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Array of Indonesian suppliers
        $suppliers = [
            [
                'code' => 'SUPP001',
                'name' => 'PT Sinar Abadi Jaya',
                'contact_person' => 'Budi Santoso',
                'email' => 'info@sinarabadijaya.co.id',
                'phone' => '+62217884321',
                'address' => 'Jl. Industri Raya No. 45',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '12940',
                'country' => 'ID',
                'tax_number' => '01.123.456.7-891.000',
                'payment_terms' => '30',
                'is_active' => true,
                'website' => 'https://sinarabadijaya.co.id',
                'industry' => 'manufacturing',
                'bank_name' => 'Bank Mandiri',
                'bank_account_number' => '1234567890',
                'bank_account_name' => 'PT Sinar Abadi Jaya',
                'notes' => 'Supplier for metal components and raw materials.',
            ],
            [
                'code' => 'SUPP002',
                'name' => 'PT Mitra Sukses Bersama',
                'contact_person' => 'Dewi Lestari',
                'email' => 'contact@mitrabb.co.id',
                'phone' => '+62218765432',
                'address' => 'Jl. Raya Bekasi KM 25',
                'city' => 'Bekasi',
                'state' => 'Jawa Barat',
                'postal_code' => '17214',
                'country' => 'ID',
                'tax_number' => '02.876.543.2-123.000',
                'payment_terms' => '15',
                'is_active' => true,
                'website' => 'https://mitrabb.co.id',
                'industry' => 'wholesale',
                'bank_name' => 'BCA',
                'bank_account_number' => '0987654321',
                'bank_account_name' => 'PT Mitra Sukses Bersama',
                'notes' => 'Distributor for electronic components.',
            ],
            [
                'code' => 'SUPP003',
                'name' => 'CV Karya Sentosa',
                'contact_person' => 'Agus Wijaya',
                'email' => 'info@karyasentosa.com',
                'phone' => '+62318765432',
                'address' => 'Jl. Raya Darmo No. 56',
                'city' => 'Surabaya',
                'state' => 'Jawa Timur',
                'postal_code' => '60226',
                'country' => 'ID',
                'tax_number' => '03.456.789.0-234.000',
                'payment_terms' => '7',
                'is_active' => true,
                'website' => 'https://karyasentosa.com',
                'industry' => 'manufacturing',
                'bank_name' => 'BNI',
                'bank_account_number' => '0123456789',
                'bank_account_name' => 'CV Karya Sentosa',
                'notes' => 'Supplier for plastic components and packaging.',
            ],
            [
                'code' => 'SUPP004',
                'name' => 'PT Teknologi Prima Indonesia',
                'contact_person' => 'Hendra Gunawan',
                'email' => 'sales@teknoprima.id',
                'phone' => '+62215432109',
                'address' => 'Jl. TB Simatupang No. 89',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '12520',
                'country' => 'ID',
                'tax_number' => '04.789.012.3-567.000',
                'payment_terms' => '30',
                'is_active' => true,
                'website' => 'https://teknoprima.id',
                'industry' => 'technology',
                'bank_name' => 'CIMB Niaga',
                'bank_account_number' => '5678901234',
                'bank_account_name' => 'PT Teknologi Prima Indonesia',
                'notes' => 'IT and technology hardware supplier.',
            ],
            [
                'code' => 'SUPP005',
                'name' => 'PT Sejahtera Food Indonesia',
                'contact_person' => 'Linda Wijaya',
                'email' => 'procurement@sejahterafood.co.id',
                'phone' => '+62213456789',
                'address' => 'Jl. Sudirman Kav. 25',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '10220',
                'country' => 'ID',
                'tax_number' => '05.234.567.8-912.000',
                'payment_terms' => 'cod',
                'is_active' => true,
                'website' => 'https://sejahterafood.co.id',
                'industry' => 'food',
                'bank_name' => 'Bank Permata',
                'bank_account_number' => '8765432109',
                'bank_account_name' => 'PT Sejahtera Food Indonesia',
                'notes' => 'Food and beverage raw materials supplier.',
            ],
            [
                'code' => 'SUPP006',
                'name' => 'PT Global Logistics Indonesia',
                'contact_person' => 'Anton Susanto',
                'email' => 'info@globallogistics.co.id',
                'phone' => '+62219876543',
                'address' => 'Jl. Yos Sudarso No. 123',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '14230',
                'country' => 'ID',
                'tax_number' => '06.345.678.9-123.000',
                'payment_terms' => '60',
                'is_active' => true,
                'website' => 'https://globallogistics.co.id',
                'industry' => 'logistics',
                'bank_name' => 'Bank BRI',
                'bank_account_number' => '2345678901',
                'bank_account_name' => 'PT Global Logistics Indonesia',
                'notes' => 'Logistics and transportation services.',
            ],
            [
                'code' => 'SUPP007',
                'name' => 'PT Konstruksi Jaya Abadi',
                'contact_person' => 'Irfan Hakim',
                'email' => 'projects@konstruksijaya.co.id',
                'phone' => '+62216543210',
                'address' => 'Jl. Gatot Subroto KM 3.5',
                'city' => 'Tangerang',
                'state' => 'Banten',
                'postal_code' => '15331',
                'country' => 'ID',
                'tax_number' => '07.456.789.0-234.000',
                'payment_terms' => '30',
                'is_active' => true,
                'website' => 'https://konstruksijaya.co.id',
                'industry' => 'construction',
                'bank_name' => 'Bank Danamon',
                'bank_account_number' => '3456789012',
                'bank_account_name' => 'PT Konstruksi Jaya Abadi',
                'notes' => 'Construction materials and equipment supplier.',
            ],
            [
                'code' => 'SUPP008',
                'name' => 'Singapore Electronics Pte Ltd',
                'contact_person' => 'Michael Tan',
                'email' => 'sales@sgelectronics.com.sg',
                'phone' => '+6565432109',
                'address' => '75 Ayer Rajah Crescent',
                'city' => 'Singapore',
                'state' => '',
                'postal_code' => '139953',
                'country' => 'SG',
                'tax_number' => 'SG200012345K',
                'payment_terms' => '30',
                'is_active' => true,
                'website' => 'https://sgelectronics.com.sg',
                'industry' => 'technology',
                'bank_name' => 'DBS Bank',
                'bank_account_number' => '0012345678',
                'bank_account_name' => 'Singapore Electronics Pte Ltd',
                'notes' => 'Imported electronic components supplier.',
            ],
            [
                'code' => 'SUPP009',
                'name' => 'PT Sarana Kimia Indonesia',
                'contact_person' => 'Siti Rahayu',
                'email' => 'sales@saranakimia.co.id',
                'phone' => '+62248765432',
                'address' => 'Jl. Imam Bonjol No. 45',
                'city' => 'Semarang',
                'state' => 'Jawa Tengah',
                'postal_code' => '50131',
                'country' => 'ID',
                'tax_number' => '09.567.890.1-345.000',
                'payment_terms' => '15',
                'is_active' => true,
                'website' => 'https://saranakimia.co.id',
                'industry' => 'manufacturing',
                'bank_name' => 'Bank Mega',
                'bank_account_number' => '4567890123',
                'bank_account_name' => 'PT Sarana Kimia Indonesia',
                'notes' => 'Chemical raw materials supplier.',
            ],
            [
                'code' => 'SUPP010',
                'name' => 'CV Tani Makmur',
                'contact_person' => 'Bambang Setiawan',
                'email' => 'info@tanimakmur.id',
                'phone' => '+62341234567',
                'address' => 'Jl. Soekarno Hatta No. 78',
                'city' => 'Malang',
                'state' => 'Jawa Timur',
                'postal_code' => '65141',
                'country' => 'ID',
                'tax_number' => '10.678.901.2-456.000',
                'payment_terms' => 'prepaid',
                'is_active' => false, // Inactive supplier example
                'website' => 'https://tanimakmur.id',
                'industry' => 'food',
                'bank_name' => 'Bank Syariah Indonesia',
                'bank_account_number' => '5678901234',
                'bank_account_name' => 'CV Tani Makmur',
                'notes' => 'Agricultural products supplier. Currently inactive due to supply chain issues.',
            ],
        ];

        // Insert supplier data
        foreach ($suppliers as $supplierData) {
            Supplier::updateOrCreate(
                ['code' => $supplierData['code']],
                $supplierData
            );
        }

        $this->command->info('Supplier data seeded successfully.');
    }
}
